service: cron-service
useDotenv: true
plugins:
  - serverless-dotenv-plugin  
  - serverless-plugin-monorepo
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 4006
  stage: ${opt:stage, 'local'}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: local

functions:
  get:
    handler: src/handler.main
    events:
      - http: GET /
      # - schedule: cron(0/5 * * * ? *)

